name: Close Unmerged SDK PRs
on:
  pull_request:
    types:
    - closed
jobs:
  update-sdk-prs:
    runs-on: ubuntu-latest
    name: Update SDK PRs
    if: ${{ contains(github.event.pull_request.labels.*.name, 'public-api') && !github.event.pull_request.merged }}
    strategy:
      matrix:
        repo:
          - realm-dotnet
          - realm-js
          - realm-cocoa
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Find SDK PR
      id: find-pr-number
      run: |
        pull_number=$(curl -s 'https://api.github.com/repos/realm/realm-dotnet/pulls?head=realm:ni/public-api-gha' -H 'Accept: application/vnd.github.v3+json' | jq '.[0].number')
        echo "::set-output name=number::$pull_number"
    - name: Close Unmerged PR
      uses: peter-evans/close-pull@cd1af3be40e42b1c6cb814502bee104471c8980b
      with:
        token: ${{ secrets.REALM_CI_PAT }}
        repository: ${{ matrix.repo }}
        pull-request-number: ${{ steps.find-pr-number.outputs.number }}
        comment: Closing this because the Core PR was closed.
        delete-branch: true
