name: Test SDKs
on:
  pull_request:
    types: [ opened, labeled, synchronize ]
jobs:
  update-dotnet:
    runs-on: ubuntu-latest
    name: Update .NET
    if: ${{ contains(github.event.pull_request.labels.*.name, 'public-api') }}
    steps:
      - uses: actions/checkout@v2
      - name: "Checkout .NET repo"
        uses: actions/checkout@v2
        with:
          repository: realm/realm-dotnet
          path: integration/dotnet
          submodules: recursive
      - name: Update submodule
        run: |
          cd integration/dotnet/wrappers/realm-core
          git remote set-branches --add 'origin' ${{ github.event.pull_request.head.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}
      - name: Create PR
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          title: ${{ github.event.pull_request.title }}
          body: Pick up realm-core/#${{ github.event.pull_request.number }}
          delete-branch: true
          path: integration/dotnet
          labels: public-api
          draft: true

